[WHD-200] Feat: 일정 캘린더 API 연동
team8901/woohakdong-web pull request #30
Opened 2024-11-08 15:13 UTC by salmonco

### 🌱 작업한 내용
- 일정 캘린더 API 연동

### 🪴 관련 이슈

- Resolved: [WHD-200](https://8901dev.atlassian.net/browse/WHD-200?atlOrigin=eyJpIjoiYzY0ZjEzMjNkN2M0NGJjMzk2MzZjOTZjOGI1N2MwNzEiLCJwIjoiaiJ9)

2024-11-08 16:15 UTC, salmonco commented
### 타입 선언 네이밍 규칙
- ~~Props
- ~~RequestData
- ~~ResponseData
- ~~ResultResponseData : { result: ~~ResponseData[] }

2024-11-12 09:16 UTC, alsdn1360 requested changes
고생하셨습니다! 앱과 달리 리액트에서는 캘린더를 어떻게 구현하는지 잘 몰랐는데..잘 해주셔서 감사합니당 👍🏻

제가 언급한 부분만 수정하실 수 있으면 수정해주시면 될 것 같습니다.

2024-11-12 09:16 UTC, alsdn1360 commented on src/libs/constant/clubSchedule.ts
> +    scheduleColor: '#6B7A8F',
Flutter에서 색상 코드를 `0xFF000000`와 같은 방식으로 이용해서 저장되는 색상 코드는 FF000000가 될 겁니다... 여기서 FF는 투명도 값입니다.

2024-11-12 09:16 UTC, alsdn1360 commented on src/pages/clubSchedule/ClubScheduleDetail.tsx
> +          <Caption2 text="일정 시각" className="text-darkGray" />
일정 상세화면 UI가 변경되었는데, Web에는 반영을 깜빡했습니다. 피그마 확인해주시면 감사하겠습니다 ㅎㅎ.. 사소한 점만 변경되었습니다.

2024-11-12 09:16 UTC, alsdn1360 commented on src/pages/clubSchedule/components/CustomCalendar.tsx
> +      }} // 달력의 시작 날짜가 바뀌면 selectedDate를 업데이트
이게 여기인지 모르겠는데, 달을 바꿀 때 그 달의 1일로 해주신거 반영해주셔서 감사합니당! 그런데 이번 달로 페이지를 이동하면 1일이 아닌 오늘로 포커스가 잡혀야 합니다.

2024-11-13 01:52 UTC, salmonco commented on src/libs/constant/clubSchedule.ts
> +    scheduleColor: '#6B7A8F',
저도 색상코드 궁금해서 찾아봤는데 `0xFF000000`가 `#000000`랑 같은 거더라구요! [참고](https://sanghyundal.tistory.com/6)

2024-11-13 01:59 UTC, salmonco commented on src/pages/clubSchedule/components/CustomCalendar.tsx
> +      }} // 달력의 시작 날짜가 바뀌면 selectedDate를 업데이트
아 그렇군요! 반영하겠습니다.

+오늘 버튼 클릭하면 오늘에 해당하는 달로 이동하고 싶은데 안 돼서 어떻게 하는지 찾아보고 있습니다..

2024-11-13 08:08 UTC, merged

2024-11-29 08:15 UTC, salmonco commented on src/pages/clubSchedule/components/CustomCalendar.tsx
> +      }} // 달력의 시작 날짜가 바뀌면 selectedDate를 업데이트
해결완료 [참고](https://velog.io/@posinity/ref-%EC%82%AC%EC%9A%A9%EB%B2%95-%EC%BA%98%EB%A6%B0%EB%8D%94-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC%EC%97%90%EC%84%9C-%EC%98%A4%EB%8A%98-%EB%B2%84%ED%8A%BC-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0)